### ISSUE TITLE
Intermittent error 

### ISSUE THREAD

**Issue by s3than** [Fallenbagel/jellyseerr#1111]
### Description

During sync

```
2024-11-19T03:06:13.384Z [debug][API]: Something went wrong retrieving movie {"errorMessage":"Cannot read properties of undefined (reading 'cast')","movieId":"xxxx"}
```

On main dashboard shows a `Movie Not Found` 

I've done a from scratch installation and the same issue presents movies appear random

Locating a Movie that has an error in the search and clicking returns a 500 error and the following log

```
2024-11-19T03:13:31.331Z [debug][API]: Something went wrong retrieving movie {"errorMessage":"Cannot read properties of undefined (reading 'cast')","movieId":"xxxx"}
 ⨯ Error
    at n (/app/.next/server/pages/movie/[movieId].js:1:24730)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e3 (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:31:594)
    at async doRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1425:30)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)
    at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1931:24)
    at async NextNodeServer.renderToResponseImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1969:32)
    at async NextNodeServer.pipeImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)
    at async invokeRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async NextCustomServer.requestHandlerImpl [as requestHandler] (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13)
```

### Version

2.1.0

### Steps to Reproduce

Show's on the dashboard as Movie Not Found.. searching for the movie and clicking on the link provided returns a 500 error 

### Platform

desktop

### Device

All

### Operating System

linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by s3than** [comment]
Some TV shows have the same issue

**Comment by Fallenbagel** [comment]
It's probably from tmdb api. Those movies/shows have been removed and you'll need to wait till cache clears.

Also I need more info on how I can reproduce this to confirm because I can't find any.

**Comment by Fallenbagel** [comment]
![Screenshot_20241119_125237_Chrome Dev.jpg](https://github.com/user-attachments/assets/b40b07fb-0ef3-4ef8-865e-ff0640773700)

If it's for something like this, it's not a bug. The movie has been removed from tmdb. You'll just have to wait till your cache clears and you'll be good.

**Comment by s3than** [comment]
One of the movies from yesterday cleared up today.. so all good.. Thank you :bow:
