### ISSUE TITLE
Bug with override rules

### ISSUE THREAD

**Issue by tmsholy** [Fallenbagel/jellyseerr#1195]
### Description

I've updated to the latest stable version and added a simple override rule to my radarr instance. The rule overrides the root folder if the language is one of two languages. 

First issue I have run into is that any movie request which triggers the override rule sends me a notification that it was automatically approved, which does not normally happen if I request it myself. Second issue, Jellyseerr attempts to add the movie to radarr and **succeeds**, but **reports it as failed** (see logs bellow) It is also added to the correct root folder. Radarr starts downloading the movie and I receive another notification that the request has failed (but It hasn't). Meanwhile the Jellyseerr UI shows a progress bar that it's being downloaded. But in the "Manage movie" side popup the request has a status of failed. Once downloaded it is properly marked as "Available" and I receive a notification that it's available. The request remains stuck in a Failed state.

I tried requesting multiple movies and despite the logs saying so, they weren't already in radarr. I have also tried requesting a movie that does not trigger the override rule and that behaves as expected. 

### Version

2.2.0

### Steps to Reproduce

1. Add an override rule for radarr
2. Request a movie that triggers the override rule
3. Observe buggy behavior

### Logs

```shell
Failed to add movie to Radarr. This might happen if the movie already exists, in which case you can safely ignore this error. {"errorMessage":"409 Conflict: {\n  \"message\": \"constraint failed
UNIQUE constraint failed: Movies.MovieMetadataId\",\n  \"description\": \"code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: Movies.MovieMetadataId
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1142
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition\\u0026 command) in /_/Dapper/SqlMapper.cs:line 1125
   at NzbDrone.Core.Datastore.BasicRepository\\u00601.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in ./Radarr.Core/Datastore/BasicRepository.cs:line 188
   at NzbDrone.Core.Datastore.BasicRepository\\u00601.Insert(TModel model) in ./Radarr.Core/Datastore/BasicRepository.cs:line 151
   at NzbDrone.Core.Movies.MovieService.AddMovie(Movie newMovie) in ./Radarr.Core/Movies/MovieService.cs:line 96
   at NzbDrone.Core.Movies.AddMovieService.AddMovie(Movie newMovie) in ./Radarr.Core/Movies/AddMovieService.cs:line 59
   at Radarr.Api.V3.Movies.MovieController.AddMovie(MovieResource moviesResource) in ./Radarr.Api.V3/Movies/MovieController.cs:line 256
   at lambda_method507(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\\u0026 next, Scope\\u0026 scope, Object\\u0026 state, Boolean\\u0026 isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   --- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\\u0026 next, Scope\\u0026 scope, Object\\u0026 state, Boolean\\u0026 isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   --- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\\u003CInvokeNextResourceFilter\\u003Eg__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State\\u0026 next, Scope\\u0026 scope, Object\\u0026 state, Boolean\\u0026 isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   --- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\\u003CInvokeAsync\\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\\u003CInvokeAsync\\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\\u003CInvoke\\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 29
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\\u003CInvoke\\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)\"\n}","options":{"profileId":8,"qualityProfileId":8,"rootFolderPath":"/data/media/movies-4k-cz","minimumAvailability":"inCinemas","title":"The Elementary School","tmdbId":18141,"year":1991,"monitored":true,"tags":[11,5],"searchNow":true}}
```

### Platform

desktop

### Database

SQLite (default)

### Device

MacBook Pro

### Operating System

macOS 15.2

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by devanteweary** [comment]
Same issue. 

My rule is for paths: If genre = animation > root path /videos/animated

- Sends me notification (email) that it is approved even though I have that unchecked.
- Immediately followed by a failed notification (email).
- Shows as failed in Jellyseerr.
- Not actually failed though - gets added to correct path in Radarr and starts downloading.
- If you click Retry in Jellyseerr, immediately corrects the Failed status.

Something I noticed:
- When requesting as admin (so it shows me the approval dialog regardless), the root path is still the default path.
- However, after clicking Request button, it still adds it to the correct/desired root path. (and shows as failed).
- Only seems to be happening with requests that meet the override rules. Default requests work 100%.

Let me know if you need logs!  
Also side note, never been more excited to update as now since the override rules solved my issues with animated (not anime) stuff being put into my "live action movies/series" folder.

**Comment by devanteweary** [comment]
Awesome turnaround time!!

I just tested my Animation rule as a non-admin test user and looks like it completely ignored the override rule.  
Just sent the request (which has Animation as a genre) to the default root folder again.

I believe it was working at 2.2.0 but now seems not to use override rules.

Here's my rule. The default root folder is `/videos/Movies/Live Action`

![image](https://github.com/user-attachments/assets/6d425fcb-0161-43f1-9fee-45a06a162c55)

**Comment by fallenbagel** [comment]
> Awesome turnaround time!!
> 
> I just tested my Animation rule as a non-admin test user and looks like it completely ignored the override rule.  
> Just sent the request (which has Animation as a genre) to the default root folder again.
> 
> I believe it was working at 2.2.0 but now seems not to use override rules.
> 
> Here's my rule. The default root folder is `/videos/Movies/Live Action`
> 
> ![image](https://github.com/user-attachments/assets/6d425fcb-0161-43f1-9fee-45a06a162c55)
> 

This is fixed in #1199

The thing to note is, override rules will not be applied to admins/advanced_request permission users. As they have the modal prior to request and if it overrides what you put in you can never have flexibility to change anything and it makes 0 sense.

 And the workflow now is: your users request something, it will get overriden before you approve.

That was always the intention of override rules but was implemented wrong

**Comment by devanteweary** [comment]
Oh wow really?

So there will never be a way to create a rule that has all animation go into an /animation folder automatically, for example?
For auto-approved users that is.
(who manually approves all their users' requests??? :P')

Dang I was all excited about this feature for a while now ha.  Oh well. :P'

Thank you guys for all your hard work.

**Comment by Fallenbagel** [comment]
> Oh wow really?
> 
> So there will never be a way to create a rule that has all animation go into an /animation folder automatically, for example?
> For auto-approved users that is.
> (As someone who tries to make it as automated as possible for my users, who manually approves all their users' requests??? :P')
> 
> Dang I was all excited about this feature for a while now ha.  Oh well. :P'
> 
> Thank you guys for all your hard work.

Wait I meant auto-approve users as in those that do not have `advances_request` modal. Those users who have auto-approval permission as in those who do not get that override modal when you request, they will still have override rules applied.

I was talking about that selection modal you get when you request as an admin or as someone with `advanced_request`. It makes no sense for their stuff to be overridden because they already choose and then send. + if we make their requests to get overridden, the admin can never ever modify a request because even if they do, when sent to *arr it will revert back to the rule.

**Comment by tmsholy** [comment]
> > Oh wow really?
> > So there will never be a way to create a rule that has all animation go into an /animation folder automatically, for example?
> > For auto-approved users that is.
> > (As someone who tries to make it as automated as possible for my users, who manually approves all their users' requests??? :P')
> > Dang I was all excited about this feature for a while now ha.  Oh well. :P'
> > Thank you guys for all your hard work.
> 
> Wait I meant auto-approve users as in those that do not have `advances_request` modal. Those users who have auto-approval permission as in those who do not get that override modal when you request, they will still have override rules applied.
> 
> I was talking about that selection modal you get when you request as an admin or as someone with `advanced_request`. It makes no sense for their stuff to be overridden because they already choose and then send. + if we make their requests to get overridden, the admin can never ever modify a request because even if they do, when sent to *arr it will revert back to the rule. Like what's the point of giving them a whole modal to choose stuff if it's just gonna get overridden anyways.
> 
> People with `auto-approve` permissions would still have their requests overriden (as in those who only see the request button but still gets their requests approved the minute they request), they will get override rules applied to them
> 
> (talking about this modal) Advanced request users: ![image](https://private-user-images.githubusercontent.com/98979876/399260454-7581070d-ca32-406a-b08d-4644ddbbd0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTA4NjUsIm5iZiI6MTczNTU1MDU2NSwicGF0aCI6Ii85ODk3OTg3Ni8zOTkyNjA0NTQtNzU4MTA3MGQtY2EzMi00MDZhLWIwOGQtNDY0NGRkYmJkMGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA5MjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllODMwM2QxNmQ0OGUzZjQ5ZGI1NGIxNGU0ZGM1M2QzNWEzOWNiYmY1NmJhZDE2YWUzMjYwNWZmZGZiNDRmMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cquewKXstWyfXfzF7v4ax0TYfvezIkrN9q2ytIoEszA)
> 
> Auto approved users (they will get override rules applied to them) ![image](https://private-user-images.githubusercontent.com/98979876/399260744-c204fe9f-a1ec-4a91-a689-76f01e5cad3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTA4NjUsIm5iZiI6MTczNTU1MDU2NSwicGF0aCI6Ii85ODk3OTg3Ni8zOTkyNjA3NDQtYzIwNGZlOWYtYTFlYy00YTkxLWE2ODktNzZmMDFlNWNhZDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA5MjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZGNkMzVmZDUyOTI2NDViNjY5MzVkYzAzNzBjNjcwYTk0N2ZmNmNmODQ5ZTU0NDIwMjZhZDU1NDAzZjNiOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F4j4KgmsDEsU5nBabaOD_-H6YVfwNZu2NfWXfbEk3iI)


Thanks for the clarification, I was in the middle of writing a whole comment about how not applying override rules for auto-approved requests would make the feature basically pointless.

This feature is great and I'm really excited that it got implemented. To make it perfect, I would like for override rules to be also applied to `advanced_request` users and admins in the form that it would at least pre-select/fill the information based on the override rules instead of having the defaults selected. This would be pretty helpful for admins so they don't have to think about making the changes every time they make a request, since they cannot take the `advanced_request` permissions away from themselves.

**Comment by Fallenbagel** [comment]
> I would like for override rules to be also applied to advanced_request users and admins in the form that it would at least pre-select/fill the information based on the override rules instead of having the defaults selected.

This is also already implemented. But targetting next major verson (v2.3.0) as its not a bug fix but an enhancement

**Comment by tmsholy** [comment]
> This is also already implemented. But targetting next minor version (v2.3.0) as its not a bug fix but an enhancement

That is awesome! Thank you and gauthier-th for the work you've put into this and also for the quick fix. Having migrated from (the basically dead) Overseerr I really appreciate the active development and engagement with the community.

**Comment by edvincent** [comment]
> The thing to note is, override rules will not be applied to admins/auto_approve permission users. As they have the modal prior to request and if it overrides what you put in you can never have flexibility to change anything and it makes 0 sense.

If I get this correctly (I might be missing something), it means that as the owner of the plex server (i.e. admin), I would never be able to leverage the feature where stuff added to the plex watchlist would be auto-downloaded if I want to use overrides? As in, it would work for every user but mine...? I don't think there's a way to make the admin account local-only, and give the owner user as many perms as other users?

Otherwise, not sure if there's something already tracking whether the request came from a watchlist sync or something else, but maybe treat those differently could be something that could be contributed? Or is there another preferred approach if I was to look into this?

**Comment by Fallenbagel** [comment]
> > The thing to note is, override rules will not be applied to admins/auto_approve permission users. As they have the modal prior to request and if it overrides what you put in you can never have flexibility to change anything and it makes 0 sense.
> 
> If I get this correctly (I might be missing something), it means that as the owner of the plex server (i.e. admin), I would never be able to leverage the feature where stuff added to the plex watchlist would be auto-downloaded if I want to use overrides? As in, it would work for every user but mine...? I don't think there's a way to make the admin account local-only, and give the owner user as many perms as other users?
> 
> Otherwise, not sure if there's something already tracking whether the request came from a watchlist sync or something else, but maybe treat those differently could be something that could be contributed? Or is there another preferred approach if I was to look into this?

Watchlist requests override will be an enhancement for the future. Currently it's only limited to your users that does not have advanced request permission.

**Comment by tyvsmith** [comment]
Spent a while debugging and was ready to report an issue before finding this thread. Agreed on the desire for the override rules to apply to users with advanced request permission. My recommendation would be that it would parse the rule and default to those settings in the advanced request dialog.

**Comment by gauthier-th** [comment]
> Spent a while debugging and was ready to report an issue before finding this thread. Agreed on the desire for the override rules to apply to users with advanced request permission. My recommendation would be that it would parse the rule and default to those settings in the advanced request dialog.

As said earlier, this is exactly what is already planned.
