### ISSUE TITLE
Jellyseer won't work after upgrade.

### ISSUE THREAD

**Issue by solarisfire** [Fallenbagel/jellyseerr#1202]
### Description

<pre>
root@astra /opt/jellyseerr # pnpm start

> jellyseerr@2.2.2 start /opt/jellyseerr
> NODE_ENV=production node dist/index.js

2024-12-30T10:17:02.976Z [info]: Starting Overseerr version 2.2.2 
2024-12-30T10:17:03.371Z [error]: TypeError: Cannot read properties of undefined (reading 'enabled')
    at /opt/jellyseerr/dist/index.js:100:29 
 ELIFECYCLE  Command failed with exit code 1.
</pre>

### Version

2.2.2

### Steps to Reproduce

Upgrade from 2.1.0 to 2.2.2:

Git pull
CYPRESS_INSTALL_BINARY=0 pnpm install --frozen-lockfile
pnpm build
pnpm start

Build works perfectly with no errors, but the application will not start.

### Logs

```shell
✔ The modules directory at "/opt/jellyseerr/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) · true
Recreating /opt/jellyseerr/node_modules
Lockfile is up to date, resolution step is skipped
Packages: +2042
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2042, reused 2022, downloaded 18, added 2042, done

dependencies:
+ @formatjs/intl-displaynames 6.2.6
+ @formatjs/intl-locale 3.1.1
+ @formatjs/intl-pluralrules 5.1.10
+ @formatjs/intl-utils 3.8.4
+ @formatjs/swc-plugin-experimental 0.4.0
+ @headlessui/react 1.7.12
+ @heroicons/react 2.0.16
+ @supercharge/request-ip 1.2.0
+ @svgr/webpack 6.5.1
+ @tanem/react-nprogress 5.0.30
+ ace-builds 1.15.2
+ bcrypt 5.1.0
+ bowser 2.11.0
+ connect-typeorm 1.1.4
+ cookie-parser 1.4.6
+ copy-to-clipboard 3.3.3
+ country-flag-icons 1.5.5
+ cronstrue 2.23.0
+ csurf 1.11.0
+ date-fns 2.29.3
+ dayjs 1.11.7
+ email-templates 9.0.0
+ email-validator 2.0.4
+ express 4.18.2
+ express-openapi-validator 4.13.8
+ express-rate-limit 6.7.0
+ express-session 1.17.3
+ formik 2.4.6
+ gravatar-url 3.1.0
+ lodash 4.17.21
+ mime 3.0.0
+ next 14.2.4
+ node-cache 5.1.2
+ node-gyp 9.3.1
+ node-schedule 2.1.1
+ nodemailer 6.9.1
+ openpgp 5.7.0
+ pg 8.11.0
+ plex-api 5.3.2
+ pug 3.0.2
+ react 18.3.1
+ react-ace 10.1.0
+ react-animate-height 2.1.2
+ react-aria 3.23.0
+ react-dom 18.3.1
+ react-intersection-observer 9.4.3
+ react-intl 6.6.8
+ react-markdown 8.0.5
+ react-popper-tooltip 4.4.2
+ react-select 5.7.0
+ react-spring 9.7.1
+ react-tailwindcss-datepicker-sct 1.3.4
+ react-toast-notifications 2.5.1
+ react-truncate-markup 5.1.2
+ react-use-clipboard 1.0.9
+ reflect-metadata 0.1.13
+ secure-random-password 0.2.3
+ semver 7.3.8
+ sharp 0.33.4
+ sqlite3 5.1.4
+ swagger-ui-express 4.6.2
+ swr 2.2.5
+ typeorm 0.3.11
+ undici 6.20.1
+ web-push 3.5.0
+ winston 3.8.2
+ winston-daily-rotate-file 4.7.1
+ xml2js 0.4.23
+ yamljs 0.3.0
+ yup 0.32.11
+ zod 3.20.6

devDependencies:
+ @commitlint/cli 17.4.4
+ @commitlint/config-conventional 17.4.4
+ @semantic-release/changelog 6.0.2
+ @semantic-release/commit-analyzer 9.0.2
+ @semantic-release/exec 6.0.3
+ @semantic-release/git 10.0.1
+ @tailwindcss/aspect-ratio 0.4.2
+ @tailwindcss/forms 0.5.3
+ @tailwindcss/typography 0.5.9
+ @types/bcrypt 5.0.0
+ @types/cookie-parser 1.4.3
+ @types/country-flag-icons 1.2.0
+ @types/csurf 1.11.2
+ @types/email-templates 8.0.4
+ @types/express 4.17.17
+ @types/express-session 1.17.6
+ @types/lodash 4.14.191
+ @types/mime 3.0.4
+ @types/node 20.14.8
+ @types/node-schedule 2.1.0
+ @types/nodemailer 6.4.7
+ @types/react 18.3.3
+ @types/react-dom 18.3.0
+ @types/react-transition-group 4.4.5
+ @types/secure-random-password 0.2.1
+ @types/semver 7.3.13
+ @types/swagger-ui-express 4.1.3
+ @types/web-push 3.3.2
+ @types/xml2js 0.4.11
+ @types/yamljs 0.2.31
+ @types/yup 0.29.14
+ @typescript-eslint/eslint-plugin 5.54.0
+ @typescript-eslint/parser 5.54.0
+ autoprefixer 10.4.13
+ commitizen 4.3.0
+ copyfiles 2.4.1
+ cy-mobile-commands 0.3.0
+ cypress 12.7.0
+ cz-conventional-changelog 3.3.0
+ eslint 8.35.0
+ eslint-config-next 14.2.4
+ eslint-config-prettier 8.6.0
+ eslint-plugin-formatjs 4.9.0
+ eslint-plugin-jsx-a11y 6.7.1
+ eslint-plugin-no-relative-import-paths 1.5.2
+ eslint-plugin-prettier 4.2.1
+ eslint-plugin-react 7.32.2
+ eslint-plugin-react-hooks 4.6.0
+ husky 8.0.3
+ lint-staged 13.1.2
+ nodemon 2.0.20
+ postcss 8.4.21
+ prettier 2.8.4
+ prettier-plugin-organize-imports 3.2.2
+ prettier-plugin-tailwindcss 0.2.3
+ semantic-release 19.0.5
+ semantic-release-docker-buildx 1.0.1
+ tailwindcss 3.2.7
+ ts-node 10.9.1
+ tsc-alias 1.8.2
+ tsconfig-paths 4.1.2
+ typescript 4.9.5

> jellyseerr@0.1.0 postinstall /opt/jellyseerr
> node postinstall-win.js


> jellyseerr@0.1.0 prepare /opt/jellyseerr
> husky install

husky - Git hooks installed

Done in 13.3s
jellyseerr@astra:/opt/jellyseerr$ pnpm build

> jellyseerr@0.1.0 build /opt/jellyseerr
> pnpm build:next && pnpm build:server


> jellyseerr@0.1.0 build:next /opt/jellyseerr
> next build

  ▲ Next.js 14.2.4
  - Experiments (use with caution):
    · scrollRestoration
    · largePageDataBytes

 ✓ Linting and checking validity of types    
   Creating an optimized production build ...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 ✓ Compiled successfully
 ✓ Collecting page data    
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
Read more: https://nextjs.org/docs/messages/opt-out-auto-static-optimization

 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (pages)                                          Size     First Load JS
┌ ƒ /                                                  41.6 kB         387 kB
├   /_app                                              0 B             207 kB
├ ƒ /404                                               908 B           208 kB
├ ƒ /blacklist                                         7.46 kB         214 kB
├ ƒ /collection/[collectionId]                         4.2 kB          298 kB
├ ƒ /discover/movies                                   1.39 kB         355 kB
├ ƒ /discover/movies/genre/[genreId]                   2.08 kB         282 kB
├ ƒ /discover/movies/genres                            3.28 kB         222 kB
├ ƒ /discover/movies/keyword                           2.13 kB         282 kB
├ ƒ /discover/movies/language/[language]               2.09 kB         282 kB
├ ƒ /discover/movies/studio/[studioId]                 2.22 kB         282 kB
├ ƒ /discover/movies/upcoming                          1.99 kB         282 kB
├ ƒ /discover/trending                                 1.97 kB         282 kB
├ ƒ /discover/tv                                       1.4 kB          355 kB
├ ƒ /discover/tv/genre/[genreId]                       2.08 kB         282 kB
├ ƒ /discover/tv/genres                                3.28 kB         222 kB
├ ƒ /discover/tv/keyword                               2.12 kB         282 kB
├ ƒ /discover/tv/language/[language]                   2.09 kB         282 kB
├ ƒ /discover/tv/network/[networkId]                   2.22 kB         282 kB
├ ƒ /discover/tv/upcoming                              1.99 kB         282 kB
├ ƒ /discover/watchlist                                2.23 kB         282 kB
├ ƒ /issues                                            7.7 kB          215 kB
├ ƒ /issues/[issueId]                                  41.3 kB         279 kB
├ ƒ /login                                             7.56 kB         267 kB
├ ƒ /login/plex/loading                                276 B           207 kB
├ ƒ /movie/[movieId]                                   8.05 kB         369 kB
├ ƒ /movie/[movieId]/cast                              2.55 kB         210 kB
├ ƒ /movie/[movieId]/crew                              2.55 kB         210 kB
├ ƒ /movie/[movieId]/recommendations                   2.12 kB         282 kB
├ ƒ /movie/[movieId]/similar                           2.11 kB         282 kB
├ ƒ /person/[personId]                                 10.3 kB         283 kB
├ ƒ /profile                                           288 B           303 kB
├ ƒ /profile/requests                                  283 B           279 kB
├ ƒ /profile/settings                                  310 B           284 kB
├ ƒ /profile/settings/main                             314 B           284 kB
├ ƒ /profile/settings/notifications/discord            2.1 kB          250 kB
├ ƒ /profile/settings/notifications/email              1.71 kB         264 kB
├ ƒ /profile/settings/notifications/pushbullet         2.3 kB          250 kB
├ ƒ /profile/settings/notifications/pushover           2.05 kB         250 kB
├ ƒ /profile/settings/notifications/telegram           2.33 kB         250 kB
├ ƒ /profile/settings/notifications/webpush            1.59 kB         236 kB
├ ƒ /profile/settings/password                         305 B           244 kB
├ ƒ /profile/settings/permissions                      301 B           225 kB
├ ƒ /profile/watchlist                                 2.22 kB         282 kB
├ ƒ /requests                                          277 B           279 kB
├ ƒ /resetpassword                                     3.44 kB         241 kB
├ ƒ /resetpassword/[guid]                              4.11 kB         242 kB
├ ƒ /search                                            2.02 kB         282 kB
├ ƒ /settings                                          338 B           293 kB
├ ƒ /settings/about                                    9.09 kB         216 kB
├ ƒ /settings/jellyfin                                 4.07 kB         246 kB
├ ƒ /settings/jobs                                     33.7 kB         241 kB
├ ƒ /settings/logs                                     8.54 kB         225 kB
├ ƒ /settings/main                                     342 B           293 kB
├ ƒ /settings/notifications/discord                    7.8 kB          251 kB
├ ƒ /settings/notifications/email                      7.05 kB         259 kB
├ ƒ /settings/notifications/gotify                     8.1 kB          251 kB
├ ƒ /settings/notifications/lunasea                    7.49 kB         250 kB
├ ƒ /settings/notifications/pushbullet                 8.11 kB         251 kB
├ ƒ /settings/notifications/pushover                   7.73 kB         251 kB
├ ƒ /settings/notifications/slack                      7.37 kB         250 kB
├ ƒ /settings/notifications/telegram                   8.66 kB         251 kB
├ ƒ /settings/notifications/webhook                    11.2 kB         254 kB
├ ƒ /settings/notifications/webpush                    8.73 kB         226 kB
├ ƒ /settings/plex                                     4.39 kB         258 kB
├ ƒ /settings/services                                 2.49 kB         308 kB
├ ƒ /settings/users                                    4.04 kB         224 kB
├ ƒ /setup                                             7.8 kB          337 kB
├ ƒ /tv/[tvId]                                         9.1 kB          370 kB
├ ƒ /tv/[tvId]/cast                                    2.54 kB         210 kB
├ ƒ /tv/[tvId]/crew                                    2.55 kB         210 kB
├ ƒ /tv/[tvId]/recommendations                         2.11 kB         282 kB
├ ƒ /tv/[tvId]/similar                                 2.12 kB         282 kB
├ ƒ /users                                             9.83 kB         250 kB
├ ƒ /users/[userId]                                    296 B           303 kB
├ ƒ /users/[userId]/requests                           451 B           279 kB
├ ƒ /users/[userId]/settings                           456 B           284 kB
├ ƒ /users/[userId]/settings/main                      460 B           284 kB
├ ƒ /users/[userId]/settings/notifications/discord     2.22 kB         250 kB
├ ƒ /users/[userId]/settings/notifications/email       1.84 kB         264 kB
├ ƒ /users/[userId]/settings/notifications/pushbullet  2.42 kB         250 kB
├ ƒ /users/[userId]/settings/notifications/pushover    2.18 kB         250 kB
├ ƒ /users/[userId]/settings/notifications/telegram    2.46 kB         251 kB
├ ƒ /users/[userId]/settings/notifications/webpush     1.72 kB         237 kB
├ ƒ /users/[userId]/settings/password                  452 B           244 kB
├ ƒ /users/[userId]/settings/permissions               443 B           225 kB
└ ƒ /users/[userId]/watchlist                          2.37 kB         282 kB
+ First Load JS shared by all                          225 kB
  ├ chunks/framework-41b0c4d7c45ae562.js               45.2 kB
  ├ chunks/main-c2ead87fc513a9fa.js                    32.3 kB
  ├ chunks/pages/_app-745c71dbf9727612.js              106 kB
  ├ chunks/webpack-ea2ee37d01e13a7e.js                 23.6 kB
  └ css/3025b60376791b1f.css                           18.3 kB

ƒ  (Dynamic)  server-rendered on demand


> jellyseerr@0.1.0 build:server /opt/jellyseerr
> tsc --project server/tsconfig.json && copyfiles -u 2 server/templates/**/*.{html,pug} dist/templates && tsc-alias -p server/tsconfig.json

(failed reverse-i-search)`start': CYPRESS_INSTALL_BINARY=0 pnpm in^Call --frozen-lockfile
jellyseerr@astra:/opt/jellyseerr$ pnpm start

> jellyseerr@0.1.0 start /opt/jellyseerr
> NODE_ENV=production node dist/index.js

2024-12-30T10:33:29.036Z [info]: Starting Overseerr version develop-local 
2024-12-30T10:33:29.440Z [error]: TypeError: Cannot read properties of undefined (reading 'enabled')
    at /opt/jellyseerr/dist/index.js:100:29 
 ELIFECYCLE  Command failed with exit code 1.
```

### Platform

desktop

### Database

SQLite (default)

### Device

Ubuntu Linux Server

### Operating System

Ubuntu 22.04.5 LTS

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by gauthier-th** [comment]
Did you remove the `.next` directory and the `dist` one?

**Comment by solarisfire** [comment]
I followed the instructions here:

https://docs.jellyseerr.dev/getting-started/buildfromsource#updating

And it didn't say to do that.

**Comment by Fallenbagel** [comment]
> I followed the instructions here:
> 
> https://docs.jellyseerr.dev/getting-started/buildfromsource#updating
> 
> And it didn't say to do that.

Because docs are not updated yet. We just made a release and usually we add to release notes too but I have not had the time. Apologies. Please do as said and report back.

This is not a bug

**Comment by solarisfire** [comment]
I removed the .next directory and the dist one and now I'm getting:

<pre>
jellyseerr@astra:/opt/jellyseerr$ pnpm start

> jellyseerr@0.1.0 start /opt/jellyseerr
> NODE_ENV=production node dist/index.js

node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module '/opt/jellyseerr/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.18.0
 ELIFECYCLE  Command failed with exit code 1.
</pre>

**Comment by solarisfire** [comment]
I re-ran "pnpm build" and it now works.

Bit it seems to have totally reset my whole install:

![image](https://github.com/user-attachments/assets/cadac227-5d53-4b6a-be7e-c94ce630ef25)

**Comment by Fallenbagel** [comment]
> I removed the .next directory and the dist one and now I'm getting:
> 
> <pre>
> jellyseerr@astra:/opt/jellyseerr$ pnpm start
> 
> > jellyseerr@0.1.0 start /opt/jellyseerr
> > NODE_ENV=production node dist/index.js
> 
> node:internal/modules/cjs/loader:1228
>   throw err;
>   ^
> 
> Error: Cannot find module '/opt/jellyseerr/dist/index.js'
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
>     at Module._load (node:internal/modules/cjs/loader:1051:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
>     at node:internal/main/run_main_module:28:49 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> 
> Node.js v20.18.0
>  ELIFECYCLE  Command failed with exit code 1.
> </pre>

Did you build after removing?

**Comment by Fallenbagel** [comment]
So did you backup your config folder?

**Comment by solarisfire** [comment]
I did not back it up,

However I have looked in /opt/jellyseerr/config and there are now two files:

settings.json and settings.old.json

I'm not sure what caused this new settings file to be created.

My database is still in-tact though.

Thanks for the help!

**Comment by Fallenbagel** [comment]
> I did not back it up,
> 
> However I have looked in /opt/jellyseerr/config and there are now two files:
> 
> settings.json and settings.old.json
> 
> I'm not sure what caused this new settings file to be created.
> 
> My database is still in-tact though.
> 
> Thanks for the help!

That's just the settings migration being extra careful by backing up your old settings before migrating incase something messes up 😄

**Comment by solarisfire** [comment]
Yeah it can be closed. Hopefully if someone else has this issue they'll find this thread and fix things!

Thanks for all your work on jellyseerr and hope you have an awesome new year!

**Comment by Avamander** [comment]
I've tried both the `latest` and `preview-nodejs_22` tags, but both are just printing `ELIFECYCLE  Command failed.` and exit randomly. Do the images themselves also need manual fixing?

```
jellyseerr  | 2025-01-19T21:00:00.481Z [debug][Jellyfin Sync]: Title already exists and no new media types found [censored]
jellyseerr  | 2025-01-19T21:00:00.501Z [debug][Jellyfin Sync]: Title already exists and no new media types found [censored] 
jellyseerr  | 2025-01-19T21:00:00.507Z [debug][Jellyfin Sync]: Title already exists and no new media types found [censored]
jellyseerr  |  ELIFECYCLE  Command failed.
```

There are no errors before the exit in the logs.

**Comment by Fallenbagel** [comment]
> I've tried both the `latest` and `preview-nodejs_22` tags, but both are just printing `ELIFECYCLE  Command failed.` and exit randomly. Do the images themselves also need manual fixing?
> 
> ```
> jellyseerr  | 2025-01-19T21:00:00.481Z [debug][Jellyfin Sync]: Title already exists and no new media types found [censored]
> jellyseerr  | 2025-01-19T21:00:00.501Z [debug][Jellyfin Sync]: Title already exists and no new media types found [censored] 
> jellyseerr  | 2025-01-19T21:00:00.507Z [debug][Jellyfin Sync]: Title already exists and no new media types found [censored]
> jellyseerr  |  ELIFECYCLE  Command failed.
> ```
> 
> There are no errors before the exit in the logs.

You should be checking docker logs.
