### ISSUE TITLE
Internal server error on V2.2.2

### ISSUE THREAD

**Issue by haath** [Fallenbagel/jellyseerr#1205]
### Description

Hello, recently I made a fresh install with `v2.2.2` and the server fails with various errors in the logs.

### Version

v2.2.2

### Steps to Reproduce

1. Start new `jellyseerr` container with the `v2.2.2` image, with the same configuration that worked for me in the past, but mounting an empty config folder to make a fresh install.
2. Go through the first-time set up, connect Jellyfin, Sonarr and Radarr.
3. Go to the Jellyseerr home page.

At this point *some* items in the library do load correctly, with thumbnails etc. But the loading at some point stops, and then the errors shown below start appearing in the docker logs.
Trying to refresh or visit any other page opens a blank white page with the text `Internal Server Error`.

### Logs

```shell
The following occurs typically once for radarr and once for sonarr:


2024-12-30T16:22:10.253Z [error][Download Tracker]: Unable to get queue from Radarr server: radarr
2024-12-30T16:22:10.255Z [error][Download Tracker]: Unable to get queue from Sonarr server: sonarr
2024-12-30T16:22:13.253Z [error][Radarr]: [Radarr] Failed to retrieve profiles: fetch failed
 ⨯ TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async M.getInitialProps (/app/.next/server/chunks/51084.js:5:34051)
    at async X (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5045)
    at async e3 (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3773)
    at async doRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1425:30)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)
    at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1931:24)
    at async NextNodeServer.renderToResponseImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1969:32)
    at async NextNodeServer.pipeImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)
    at async invokeRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async NextCustomServer.requestHandlerImpl [as requestHandler] (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13) {
  [cause]: ConnectTimeoutError: Connect Timeout Error (attempted address: localhost:5055, timeout: 10000ms)
      at onConnectTimeout (/app/node_modules/.pnpm/undici@6.20.1/node_modules/undici/lib/core/connect.js:232:24)
      at Immediate._onImmediate (/app/node_modules/.pnpm/undici@6.20.1/node_modules/undici/lib/core/connect.js:206:11)
      at process.processImmediate (node:internal/timers:483:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

The following occurs multiple times:

```
2024-12-30T16:25:10.558Z [error][Jellyfin Sync]: Failed to process Jellyfin item, id: ce1f047a9208a1a95996aff62034e58d {"errorMessage":"[TMDB] Failed to find media using external IMDb ID: [TMDB] Failed to find by external ID: fetch failed","jellyfinitem":{"Name":"The Report","ServerId":"56e4a68ed1a446b99cf5d06261164d32","Id":"ce1f047a9208a1a95996aff62034e58d","HasSubtitles":true,"Container":"mkv","PremiereDate":"2019-09-12T00:00:00.0000000Z","CriticRating":82,"OfficialRating":"R","ChannelId":null,"CommunityRating":7.033,"RunTimeTicks":71814080000,"ProductionYear":2019,"IsFolder":false,"Type":"Movie","UserData":{"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"524348","ItemId":"00000000000000000000000000000000"},"ChildCount":0,"VideoType":"VideoFile","ImageTags":{"Primary":"312d9d787450471073d4fd2a4d1409db","Logo":"0c53bf6571cc208d4157574cef777f99","Thumb":"585f86dea50bbc007339f7542e3f43ec"},"BackdropImageTags":["01405a62bba0511a60d910278e251800"],"ImageBlurHashes":{"Backdrop":{"01405a62bba0511a60d910278e251800":"WcKd}Lxu?bt7IT_3_3WB%M%MRjaz%MxuxuxuRjIU~qWB%MxuRjay"},"Primary":{"312d9d787450471073d4fd2a4d1409db":"ddNm.,-q~q?v?bkCRjs:%MWBIUkC%Mj[t7t7t7ayWBj["},"Logo":{"0c53bf6571cc208d4157574cef777f99":"O~PGKqn%XSkWjZoffkoffQj[fQfQfQfQ_NbbnOjFbHayjt"},"Thumb":{"585f86dea50bbc007339f7542e3f43ec":"NbIE^aRj?bt7WB~q-;xu-;xut7ofs:xu%MxuxuRj"}},"LocationType":"FileSystem","MediaType":"Video"}}
```
```


### Platform

desktop

### Database

None

### Device

MacBook Pro

### Operating System

MacOS

### Browser

Firefox

### Additional Context

The same error was first encountered when updating my instance from `1.9` to `2.2`.
I made a fresh install to rule out that it was a migration issue.

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Docker?

**Comment by Paynayt** [comment]
Thanks you so much, i was struggling like 10 days to fix this. 👍
