### ISSUE TITLE
[bug] Error: SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by Book-reader** [Fallenbagel/jellyseerr#452]
### Description

attempting to run jellyseerr in a docker container gives an error saying the sqlite database is locked causing the container to restart. the web ui does not show up.

### Version

1.6.0 docker

### Steps to Reproduce

1. Run container with `docker run -d  --name jellyseerr  -e TZ=Pacific/Auckland  -p 5055:5055  -v /docker/jellyseerr/:/app/config  --restart unless-stopped  fallenbagel/jellyseerr:latest`
2. Run `docker logs jellyseerr`
3. see error

### Logs

```shell
yarn run v1.22.19
$ NODE_ENV=production node dist/index.js
2023-08-15T01:43:17.212Z [info]: Commit Tag: $GIT_SHA 
2023-08-15T01:43:17.577Z [info]: Starting Overseerr version 1.6.0 
warn  - You have enabled experimental features (scrollRestoration, largePageDataBytes) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

2023-08-15T01:43:19.375Z [error]: Error: SQLITE_BUSY: database is locked
--> in Statement#run([Function: replacement])
    at Database.<anonymous> (/app/node_modules/sqlite3/lib/sqlite3.js:76:19)
    at Database.<anonymous> (/app/node_modules/sqlite3/lib/sqlite3.js:20:19)
    at /app/node_modules/typeorm/driver/sqlite/SqliteDriver.js:109:36
    at new Promise (<anonymous>)
    at run (/app/node_modules/typeorm/driver/sqlite/SqliteDriver.js:108:20)
    at SqliteDriver.createDatabaseConnection (/app/node_modules/typeorm/driver/sqlite/SqliteDriver.js:122:19)
    at async SqliteDriver.connect (/app/node_modules/typeorm/driver/sqlite-abstract/AbstractSqliteDriver.js:170:35)
    at async DataSource.initialize (/app/node_modules/typeorm/data-source/DataSource.js:129:9)
    at async /app/dist/index.js:72:26 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Platform

desktop

### Device

PC

### Operating System

Debian 12

### Browser

N/A

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Book-reader** [comment]
solved.
it was an issue with my samba shares. i needed to mount with nolock
